// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4Q_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_gl_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_gl_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_one_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_one_gl_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_one_gl_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_one_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_one_z_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_sdk_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_sdk_gl_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_sdk_gl_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_sdk_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_sdk_z_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gencline_z_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4hi_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4Q_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Q_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_gl_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_gl_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_gl_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_gl_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_one_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_one_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_one_gl_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_one_gl_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_one_gl_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_one_gl_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_one_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_one_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_one_z_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_one_z_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_sdk_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_sdk_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_sdk_gl_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_sdk_gl_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_sdk_gl_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_sdk_gl_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_sdk_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_sdk_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_sdk_z_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_sdk_z_mod, 0},
    {"_rcpp_module_boot_stan_fit4gencline_z_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gencline_z_mod, 0},
    {"_rcpp_module_boot_stan_fit4hi_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4hi_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bgchm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
