// Generated by rstantools.  Do not edit by hand.

/*
    bgchm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bgchm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bgchm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_p_gl_mix_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 58> locations_array__ =
  {" (found before start of program)",
  " (in 'p_gl_mix', line 33, column 1 to column 32)",
  " (in 'p_gl_mix', line 34, column 1 to column 32)",
  " (in 'p_gl_mix', line 40, column 3 to column 76)",
  " (in 'p_gl_mix', line 38, column 16 to line 41, column 3)",
  " (in 'p_gl_mix', line 38, column 2 to line 41, column 3)",
  " (in 'p_gl_mix', line 44, column 3 to column 76)",
  " (in 'p_gl_mix', line 42, column 16 to line 45, column 3)",
  " (in 'p_gl_mix', line 42, column 2 to line 45, column 3)",
  " (in 'p_gl_mix', line 37, column 14 to line 46, column 2)",
  " (in 'p_gl_mix', line 37, column 1 to line 46, column 2)",
  " (in 'p_gl_mix', line 49, column 2 to column 40)",
  " (in 'p_gl_mix', line 50, column 2 to column 40)",
  " (in 'p_gl_mix', line 47, column 14 to line 51, column 2)",
  " (in 'p_gl_mix', line 47, column 1 to line 51, column 2)",
  " (in 'p_gl_mix', line 20, column 1 to column 7)",
  " (in 'p_gl_mix', line 21, column 1 to column 8)",
  " (in 'p_gl_mix', line 22, column 1 to column 8)",
  " (in 'p_gl_mix', line 23, column 29 to column 31)",
  " (in 'p_gl_mix', line 23, column 33 to column 34)",
  " (in 'p_gl_mix', line 23, column 1 to column 36)",
  " (in 'p_gl_mix', line 24, column 29 to column 31)",
  " (in 'p_gl_mix', line 24, column 33 to column 34)",
  " (in 'p_gl_mix', line 24, column 1 to column 36)",
  " (in 'p_gl_mix', line 25, column 29 to column 31)",
  " (in 'p_gl_mix', line 25, column 33 to column 34)",
  " (in 'p_gl_mix', line 25, column 1 to column 36)",
  " (in 'p_gl_mix', line 26, column 29 to column 31)",
  " (in 'p_gl_mix', line 26, column 33 to column 34)",
  " (in 'p_gl_mix', line 26, column 1 to column 36)",
  " (in 'p_gl_mix', line 27, column 29 to column 31)",
  " (in 'p_gl_mix', line 27, column 33 to column 34)",
  " (in 'p_gl_mix', line 27, column 1 to column 36)",
  " (in 'p_gl_mix', line 28, column 29 to column 31)",
  " (in 'p_gl_mix', line 28, column 33 to column 34)",
  " (in 'p_gl_mix', line 28, column 1 to column 36)",
  " (in 'p_gl_mix', line 29, column 31 to column 33)",
  " (in 'p_gl_mix', line 29, column 35 to column 36)",
  " (in 'p_gl_mix', line 29, column 1 to column 38)",
  " (in 'p_gl_mix', line 30, column 31 to column 33)",
  " (in 'p_gl_mix', line 30, column 35 to column 36)",
  " (in 'p_gl_mix', line 30, column 1 to column 38)",
  " (in 'p_gl_mix', line 33, column 26 to column 27)",
  " (in 'p_gl_mix', line 34, column 26 to column 27)",
  " (in 'p_gl_mix', line 4, column 2 to column 12)",
  " (in 'p_gl_mix', line 14, column 10 to column 19)",
  " (in 'p_gl_mix', line 13, column 16 to line 15, column 10)",
  " (in 'p_gl_mix', line 10, column 3 to column 30)",
  " (in 'p_gl_mix', line 12, column 10 to column 54)",
  " (in 'p_gl_mix', line 9, column 19 to line 13, column 10)",
  " (in 'p_gl_mix', line 9, column 9 to line 15, column 10)",
  " (in 'p_gl_mix', line 6, column 10 to column 48)",
  " (in 'p_gl_mix', line 7, column 10 to column 74)",
  " (in 'p_gl_mix', line 8, column 10 to column 63)",
  " (in 'p_gl_mix', line 5, column 11 to line 9, column 3)",
  " (in 'p_gl_mix', line 5, column 2 to line 15, column 10)",
  " (in 'p_gl_mix', line 16, column 2 to column 14)",
  " (in 'p_gl_mix', line 3, column 60 to line 17, column 2)"};
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
calc_lik(const T0__& gl0, const T1__& gl1, const T2__& gl2, const T3__& p,
         const int& pl, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
calc_lik(const T0__& gl0, const T1__& gl1, const T2__& gl2, const T3__& p,
         const int& pl, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ prob = DUMMY_VAR__;
    current_statement__ = 55;
    if (stan::math::logical_eq(pl, 2)) {
      current_statement__ = 51;
      prob = ((stan::math::log(gl0) + stan::math::log((1 - p))) +
        stan::math::log((1 - p)));
      current_statement__ = 52;
      prob = stan::math::log_sum_exp(prob, (((stan::math::log(gl1) +
               stan::math::log(2)) + stan::math::log(p)) +
               stan::math::log((1 - p))));
      current_statement__ = 53;
      prob = stan::math::log_sum_exp(prob, ((stan::math::log(gl2) +
               stan::math::log(p)) + stan::math::log(p)));
    } else {
      current_statement__ = 50;
      if (stan::math::logical_eq(pl, 1)) {
        current_statement__ = 47;
        prob = (stan::math::log(gl0) + stan::math::log((1 - p)));
        current_statement__ = 48;
        prob = stan::math::log_sum_exp(prob, (stan::math::log(gl1) +
                 stan::math::log(p)));
      } else {
        current_statement__ = 45;
        prob = 0;
      }
    }
    current_statement__ = 56;
    return prob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_p_gl_mix final : public model_base_crtp<model_p_gl_mix> {
private:
  int L;
  int N0;
  int N1;
  std::vector<std::vector<double>> GL00;
  std::vector<std::vector<double>> GL10;
  std::vector<std::vector<double>> GL01;
  std::vector<std::vector<double>> GL11;
  std::vector<std::vector<double>> GL02;
  std::vector<std::vector<double>> GL12;
  std::vector<std::vector<int>> ploidy0;
  std::vector<std::vector<int>> ploidy1;
public:
  ~model_p_gl_mix() {}
  model_p_gl_mix(stan::io::var_context& context__, unsigned int
                 random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_p_gl_mix_namespace::model_p_gl_mix";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 15;
      context__.validate_dims("data initialization", "L", "int",
        std::vector<size_t>{});
      L = std::numeric_limits<int>::min();
      current_statement__ = 15;
      L = context__.vals_i("L")[(1 - 1)];
      current_statement__ = 16;
      context__.validate_dims("data initialization", "N0", "int",
        std::vector<size_t>{});
      N0 = std::numeric_limits<int>::min();
      current_statement__ = 16;
      N0 = context__.vals_i("N0")[(1 - 1)];
      current_statement__ = 17;
      context__.validate_dims("data initialization", "N1", "int",
        std::vector<size_t>{});
      N1 = std::numeric_limits<int>::min();
      current_statement__ = 17;
      N1 = context__.vals_i("N1")[(1 - 1)];
      current_statement__ = 18;
      stan::math::validate_non_negative_index("GL00", "N0", N0);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("GL00", "L", L);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "GL00", "double",
        std::vector<size_t>{static_cast<size_t>(N0), static_cast<size_t>(L)});
      GL00 = std::vector<std::vector<double>>(N0,
               std::vector<double>(L,
                 std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> GL00_flat__;
        current_statement__ = 20;
        GL00_flat__ = context__.vals_r("GL00");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 20;
          for (int sym2__ = 1; sym2__ <= N0; ++sym2__) {
            current_statement__ = 20;
            stan::model::assign(GL00, GL00_flat__[(pos__ - 1)],
              "assigning variable GL00", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 20;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "GL00", GL00, 0);
      current_statement__ = 20;
      stan::math::check_less_or_equal(function__, "GL00", GL00, 2);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("GL10", "N1", N1);
      current_statement__ = 22;
      stan::math::validate_non_negative_index("GL10", "L", L);
      current_statement__ = 23;
      context__.validate_dims("data initialization", "GL10", "double",
        std::vector<size_t>{static_cast<size_t>(N1), static_cast<size_t>(L)});
      GL10 = std::vector<std::vector<double>>(N1,
               std::vector<double>(L,
                 std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> GL10_flat__;
        current_statement__ = 23;
        GL10_flat__ = context__.vals_r("GL10");
        current_statement__ = 23;
        pos__ = 1;
        current_statement__ = 23;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 23;
          for (int sym2__ = 1; sym2__ <= N1; ++sym2__) {
            current_statement__ = 23;
            stan::model::assign(GL10, GL10_flat__[(pos__ - 1)],
              "assigning variable GL10", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 23;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "GL10", GL10, 0);
      current_statement__ = 23;
      stan::math::check_less_or_equal(function__, "GL10", GL10, 2);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("GL01", "N0", N0);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("GL01", "L", L);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "GL01", "double",
        std::vector<size_t>{static_cast<size_t>(N0), static_cast<size_t>(L)});
      GL01 = std::vector<std::vector<double>>(N0,
               std::vector<double>(L,
                 std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> GL01_flat__;
        current_statement__ = 26;
        GL01_flat__ = context__.vals_r("GL01");
        current_statement__ = 26;
        pos__ = 1;
        current_statement__ = 26;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 26;
          for (int sym2__ = 1; sym2__ <= N0; ++sym2__) {
            current_statement__ = 26;
            stan::model::assign(GL01, GL01_flat__[(pos__ - 1)],
              "assigning variable GL01", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 26;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "GL01", GL01, 0);
      current_statement__ = 26;
      stan::math::check_less_or_equal(function__, "GL01", GL01, 2);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("GL11", "N1", N1);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("GL11", "L", L);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "GL11", "double",
        std::vector<size_t>{static_cast<size_t>(N1), static_cast<size_t>(L)});
      GL11 = std::vector<std::vector<double>>(N1,
               std::vector<double>(L,
                 std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> GL11_flat__;
        current_statement__ = 29;
        GL11_flat__ = context__.vals_r("GL11");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 29;
          for (int sym2__ = 1; sym2__ <= N1; ++sym2__) {
            current_statement__ = 29;
            stan::model::assign(GL11, GL11_flat__[(pos__ - 1)],
              "assigning variable GL11", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 29;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "GL11", GL11, 0);
      current_statement__ = 29;
      stan::math::check_less_or_equal(function__, "GL11", GL11, 2);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("GL02", "N0", N0);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("GL02", "L", L);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "GL02", "double",
        std::vector<size_t>{static_cast<size_t>(N0), static_cast<size_t>(L)});
      GL02 = std::vector<std::vector<double>>(N0,
               std::vector<double>(L,
                 std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> GL02_flat__;
        current_statement__ = 32;
        GL02_flat__ = context__.vals_r("GL02");
        current_statement__ = 32;
        pos__ = 1;
        current_statement__ = 32;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 32;
          for (int sym2__ = 1; sym2__ <= N0; ++sym2__) {
            current_statement__ = 32;
            stan::model::assign(GL02, GL02_flat__[(pos__ - 1)],
              "assigning variable GL02", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 32;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "GL02", GL02, 0);
      current_statement__ = 32;
      stan::math::check_less_or_equal(function__, "GL02", GL02, 2);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("GL12", "N1", N1);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("GL12", "L", L);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "GL12", "double",
        std::vector<size_t>{static_cast<size_t>(N1), static_cast<size_t>(L)});
      GL12 = std::vector<std::vector<double>>(N1,
               std::vector<double>(L,
                 std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> GL12_flat__;
        current_statement__ = 35;
        GL12_flat__ = context__.vals_r("GL12");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 35;
          for (int sym2__ = 1; sym2__ <= N1; ++sym2__) {
            current_statement__ = 35;
            stan::model::assign(GL12, GL12_flat__[(pos__ - 1)],
              "assigning variable GL12", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 35;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "GL12", GL12, 0);
      current_statement__ = 35;
      stan::math::check_less_or_equal(function__, "GL12", GL12, 2);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("ploidy0", "N0", N0);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("ploidy0", "L", L);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "ploidy0", "int",
        std::vector<size_t>{static_cast<size_t>(N0), static_cast<size_t>(L)});
      ploidy0 = std::vector<std::vector<int>>(N0,
                  std::vector<int>(L, std::numeric_limits<int>::min()));
      {
        std::vector<int> ploidy0_flat__;
        current_statement__ = 38;
        ploidy0_flat__ = context__.vals_i("ploidy0");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 38;
          for (int sym2__ = 1; sym2__ <= N0; ++sym2__) {
            current_statement__ = 38;
            stan::model::assign(ploidy0, ploidy0_flat__[(pos__ - 1)],
              "assigning variable ploidy0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 38;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "ploidy0", ploidy0, 0);
      current_statement__ = 38;
      stan::math::check_less_or_equal(function__, "ploidy0", ploidy0, 2);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("ploidy1", "N1", N1);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("ploidy1", "L", L);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "ploidy1", "int",
        std::vector<size_t>{static_cast<size_t>(N1), static_cast<size_t>(L)});
      ploidy1 = std::vector<std::vector<int>>(N1,
                  std::vector<int>(L, std::numeric_limits<int>::min()));
      {
        std::vector<int> ploidy1_flat__;
        current_statement__ = 41;
        ploidy1_flat__ = context__.vals_i("ploidy1");
        current_statement__ = 41;
        pos__ = 1;
        current_statement__ = 41;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 41;
          for (int sym2__ = 1; sym2__ <= N1; ++sym2__) {
            current_statement__ = 41;
            stan::model::assign(ploidy1, ploidy1_flat__[(pos__ - 1)],
              "assigning variable ploidy1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 41;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "ploidy1", ploidy1, 0);
      current_statement__ = 41;
      stan::math::check_less_or_equal(function__, "ploidy1", ploidy1, 2);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("P0", "L", L);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("P1", "L", L);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = L + L;
  }
  inline std::string model_name() const final {
    return "model_p_gl_mix";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_p_gl_mix_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> P0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(L, DUMMY_VAR__);
      current_statement__ = 1;
      P0 = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__, L);
      Eigen::Matrix<local_scalar_t__,-1,1> P1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(L, DUMMY_VAR__);
      current_statement__ = 2;
      P1 = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__, L);
      {
        current_statement__ = 10;
        for (int i = 1; i <= L; ++i) {
          current_statement__ = 5;
          for (int j = 1; j <= N0; ++j) {
            current_statement__ = 3;
            lp_accum__.add(calc_lik(
                             stan::model::rvalue(GL00, "GL00",
                               stan::model::index_uni(j),
                               stan::model::index_uni(i)),
                             stan::model::rvalue(GL01, "GL01",
                               stan::model::index_uni(j),
                               stan::model::index_uni(i)),
                             stan::model::rvalue(GL02, "GL02",
                               stan::model::index_uni(j),
                               stan::model::index_uni(i)),
                             stan::model::rvalue(P0, "P0",
                               stan::model::index_uni(i)),
                             stan::model::rvalue(ploidy0, "ploidy0",
                               stan::model::index_uni(j),
                               stan::model::index_uni(i)), pstream__));
          }
          current_statement__ = 8;
          for (int j = 1; j <= N1; ++j) {
            current_statement__ = 6;
            lp_accum__.add(calc_lik(
                             stan::model::rvalue(GL10, "GL10",
                               stan::model::index_uni(j),
                               stan::model::index_uni(i)),
                             stan::model::rvalue(GL11, "GL11",
                               stan::model::index_uni(j),
                               stan::model::index_uni(i)),
                             stan::model::rvalue(GL12, "GL12",
                               stan::model::index_uni(j),
                               stan::model::index_uni(i)),
                             stan::model::rvalue(P1, "P1",
                               stan::model::index_uni(i)),
                             stan::model::rvalue(ploidy1, "ploidy1",
                               stan::model::index_uni(j),
                               stan::model::index_uni(i)), pstream__));
          }
        }
        current_statement__ = 14;
        for (int i = 1; i <= L; ++i) {
          current_statement__ = 11;
          lp_accum__.add(stan::math::beta_lpdf<false>(
                           stan::model::rvalue(P0, "P0",
                             stan::model::index_uni(i)), 0.5, 0.5));
          current_statement__ = 12;
          lp_accum__.add(stan::math::beta_lpdf<false>(
                           stan::model::rvalue(P1, "P1",
                             stan::model::index_uni(i)), 0.5, 0.5));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_p_gl_mix_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> P0 =
        Eigen::Matrix<double,-1,1>::Constant(L,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      P0 = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__, L);
      Eigen::Matrix<double,-1,1> P1 =
        Eigen::Matrix<double,-1,1>::Constant(L,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      P1 = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__, L);
      out__.write(P0);
      out__.write(P1);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> P0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(L, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(P0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(L),
        "assigning variable P0");
      out__.write_free_lub(0, 1, P0);
      Eigen::Matrix<local_scalar_t__,-1,1> P1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(L, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(P1,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(L),
        "assigning variable P1");
      out__.write_free_lub(0, 1, P1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "P0", "double",
        std::vector<size_t>{static_cast<size_t>(L)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "P1", "double",
        std::vector<size_t>{static_cast<size_t>(L)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> P0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(L, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> P0_flat__;
        current_statement__ = 1;
        P0_flat__ = context__.vals_r("P0");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(P0, P0_flat__[(pos__ - 1)],
            "assigning variable P0", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(0, 1, P0);
      Eigen::Matrix<local_scalar_t__,-1,1> P1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(L, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> P1_flat__;
        current_statement__ = 2;
        P1_flat__ = context__.vals_r("P1");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(P1, P1_flat__[(pos__ - 1)],
            "assigning variable P1", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(0, 1, P1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"P0", "P1"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(L)},
                std::vector<size_t>{static_cast<size_t>(L)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
      param_names__.emplace_back(std::string() + "P0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
      param_names__.emplace_back(std::string() + "P1" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
      param_names__.emplace_back(std::string() + "P0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
      param_names__.emplace_back(std::string() + "P1" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"P0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(L) + "},\"block\":\"parameters\"},{\"name\":\"P1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(L) + "},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"P0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(L) + "},\"block\":\"parameters\"},{\"name\":\"P1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(L) + "},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (L + L);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (L + L);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_p_gl_mix_namespace::model_p_gl_mix;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_p_gl_mix_namespace::profiles__;
}
#endif
#endif
