// Generated by rstantools.  Do not edit by hand.

/*
    bgchm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bgchm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bgchm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_geocline_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'geocline', line 16, column 4 to column 20)",
                                                      " (in 'geocline', line 17, column 4 to column 19)",
                                                      " (in 'geocline', line 18, column 4 to column 12)",
                                                      " (in 'geocline', line 19, column 4 to column 24)",
                                                      " (in 'geocline', line 20, column 4 to column 23)",
                                                      " (in 'geocline', line 23, column 4 to column 16)",
                                                      " (in 'geocline', line 26, column 8 to column 35)",
                                                      " (in 'geocline', line 25, column 17 to line 27, column 5)",
                                                      " (in 'geocline', line 25, column 4 to line 27, column 5)",
                                                      " (in 'geocline', line 34, column 7 to column 73)",
                                                      " (in 'geocline', line 33, column 2 to line 34, column 73)",
                                                      " (in 'geocline', line 31, column 18 to line 35, column 10)",
                                                      " (in 'geocline', line 31, column 5 to line 35, column 10)",
                                                      " (in 'geocline', line 30, column 14 to line 36, column 2)",
                                                      " (in 'geocline', line 30, column 1 to line 36, column 2)",
                                                      " (in 'geocline', line 39, column 5 to column 49)",
                                                      " (in 'geocline', line 40, column 5 to column 45)",
                                                      " (in 'geocline', line 38, column 14 to line 41, column 2)",
                                                      " (in 'geocline', line 38, column 1 to line 41, column 2)",
                                                      " (in 'geocline', line 42, column 1 to column 36)",
                                                      " (in 'geocline', line 43, column 1 to column 41)",
                                                      " (in 'geocline', line 44, column 1 to column 40)",
                                                      " (in 'geocline', line 2, column 1 to column 7)",
                                                      " (in 'geocline', line 3, column 1 to column 7)",
                                                      " (in 'geocline', line 4, column 10 to column 11)",
                                                      " (in 'geocline', line 4, column 1 to column 13)",
                                                      " (in 'geocline', line 5, column 8 to column 9)",
                                                      " (in 'geocline', line 5, column 11 to column 12)",
                                                      " (in 'geocline', line 5, column 1 to column 14)",
                                                      " (in 'geocline', line 6, column 1 to column 9)",
                                                      " (in 'geocline', line 7, column 1 to column 9)",
                                                      " (in 'geocline', line 10, column 4 to column 13)",
                                                      " (in 'geocline', line 11, column 4 to column 13)",
                                                      " (in 'geocline', line 12, column 4 to column 22)",
                                                      " (in 'geocline', line 13, column 4 to column 26)",
                                                      " (in 'geocline', line 16, column 11 to column 12)",
                                                      " (in 'geocline', line 17, column 11 to column 12)",
                                                      " (in 'geocline', line 23, column 11 to column 12)"};
#include <stan_meta_header.hpp>
class model_geocline final : public model_base_crtp<model_geocline> {
private:
  int L;
  int J;
  std::vector<double> geo;
  std::vector<std::vector<double>> Y;
  double lb;
  double ub;
  double sdg;
  double sds;
 
public:
  ~model_geocline() { }
  
  inline std::string model_name() const final { return "model_geocline"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_geocline(stan::io::var_context& context__,
                 unsigned int random_seed__ = 0,
                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_geocline_namespace::model_geocline";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 23;
      context__.validate_dims("data initialization","L","int",
          context__.to_vec());
      L = std::numeric_limits<int>::min();
      
      current_statement__ = 23;
      L = context__.vals_i("L")[(1 - 1)];
      current_statement__ = 24;
      context__.validate_dims("data initialization","J","int",
          context__.to_vec());
      J = std::numeric_limits<int>::min();
      
      current_statement__ = 24;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 25;
      validate_non_negative_index("geo", "J", J);
      current_statement__ = 26;
      context__.validate_dims("data initialization","geo","double",
          context__.to_vec(J));
      geo = std::vector<double>(J, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 26;
      assign(geo, nil_index_list(), context__.vals_r("geo"),
        "assigning variable geo");
      current_statement__ = 27;
      validate_non_negative_index("Y", "J", J);
      current_statement__ = 28;
      validate_non_negative_index("Y", "L", L);
      current_statement__ = 29;
      context__.validate_dims("data initialization","Y","double",
          context__.to_vec(J, L));
      Y = std::vector<std::vector<double>>(J, std::vector<double>(L, std::numeric_limits<double>::quiet_NaN()));
      
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 29;
        assign(Y_flat__, nil_index_list(), context__.vals_r("Y"),
          "assigning variable Y_flat__");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 29;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 29;
            assign(Y,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              Y_flat__[(pos__ - 1)], "assigning variable Y");
            current_statement__ = 29;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 30;
      context__.validate_dims("data initialization","lb","double",
          context__.to_vec());
      lb = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 30;
      lb = context__.vals_r("lb")[(1 - 1)];
      current_statement__ = 31;
      context__.validate_dims("data initialization","ub","double",
          context__.to_vec());
      ub = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 31;
      ub = context__.vals_r("ub")[(1 - 1)];
      current_statement__ = 32;
      sdg = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 33;
      sds = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 34;
      sdg = (3 * sd(geo));
      current_statement__ = 35;
      sds = ((1.5 * 4) / sd(geo));
      current_statement__ = 36;
      validate_non_negative_index("slope", "L", L);
      current_statement__ = 37;
      validate_non_negative_index("cent", "L", L);
      current_statement__ = 38;
      validate_non_negative_index("w", "L", L);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += L;
      num_params_r__ += L;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_geocline_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> slope;
      slope = Eigen::Matrix<local_scalar_t__, -1, 1>(L);
      stan::math::fill(slope, DUMMY_VAR__);
      
      current_statement__ = 1;
      slope = in__.vector(L);
      Eigen::Matrix<local_scalar_t__, -1, 1> cent;
      cent = Eigen::Matrix<local_scalar_t__, -1, 1>(L);
      stan::math::fill(cent, DUMMY_VAR__);
      
      current_statement__ = 2;
      cent = in__.vector(L);
      local_scalar_t__ mu;
      mu = DUMMY_VAR__;
      
      current_statement__ = 3;
      mu = in__.scalar();
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      current_statement__ = 4;
      sigma = in__.scalar();
      current_statement__ = 4;
      if (jacobian__) {
        current_statement__ = 4;
        sigma = stan::math::lb_constrain(sigma, 0, lp__);
      } else {
        current_statement__ = 4;
        sigma = stan::math::lb_constrain(sigma, 0);
      }
      local_scalar_t__ serr;
      serr = DUMMY_VAR__;
      
      current_statement__ = 5;
      serr = in__.scalar();
      current_statement__ = 5;
      if (jacobian__) {
        current_statement__ = 5;
        serr = stan::math::lb_constrain(serr, 0, lp__);
      } else {
        current_statement__ = 5;
        serr = stan::math::lb_constrain(serr, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> w;
      w = Eigen::Matrix<local_scalar_t__, -1, 1>(L);
      stan::math::fill(w, DUMMY_VAR__);
      
      current_statement__ = 9;
      for (int i = 1; i <= L; ++i) {
        current_statement__ = 7;
        assign(w, cons_list(index_uni(i), nil_index_list()),
          (1 / (0.25 * slope[(i - 1)])), "assigning variable w");}
      {
        current_statement__ = 15;
        for (int i = 1; i <= L; ++i) {
          current_statement__ = 13;
          for (int j = 1; j <= J; ++j) {
            current_statement__ = 11;
            if ((primitive_value(logical_gt(Y[(j - 1)][(i - 1)], lb)) &&
                primitive_value(logical_lt(Y[(j - 1)][(i - 1)], ub)))) {
              current_statement__ = 10;
              lp_accum__.add(
                normal_lpdf<false>(Y[(j - 1)][(i - 1)],
                  (cent[(i - 1)] + (slope[(i - 1)] * geo[(j - 1)])), serr));
            } }}
        current_statement__ = 19;
        for (int i = 1; i <= L; ++i) {
          current_statement__ = 16;
          lp_accum__.add(normal_lpdf<false>(slope[(i - 1)], mu, sigma));
          current_statement__ = 17;
          lp_accum__.add(normal_lpdf<false>(cent[(i - 1)], 0, sdg));}
        current_statement__ = 20;
        lp_accum__.add(normal_lpdf<false>(mu, 0, sds));
        current_statement__ = 21;
        lp_accum__.add(gamma_lpdf<false>(sigma, 0.1, 0.01));
        current_statement__ = 22;
        lp_accum__.add(gamma_lpdf<false>(serr, 0.1, 0.01));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_geocline_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> slope;
      slope = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(slope, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      slope = in__.vector(L);
      Eigen::Matrix<double, -1, 1> cent;
      cent = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(cent, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      cent = in__.vector(L);
      double mu;
      mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu = in__.scalar();
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      sigma = in__.scalar();
      current_statement__ = 4;
      sigma = stan::math::lb_constrain(sigma, 0);
      double serr;
      serr = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      serr = in__.scalar();
      current_statement__ = 5;
      serr = stan::math::lb_constrain(serr, 0);
      Eigen::Matrix<double, -1, 1> w;
      w = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(w, std::numeric_limits<double>::quiet_NaN());
      
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        vars__.emplace_back(slope[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        vars__.emplace_back(cent[(sym1__ - 1)]);}
      vars__.emplace_back(mu);
      vars__.emplace_back(sigma);
      vars__.emplace_back(serr);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 9;
      for (int i = 1; i <= L; ++i) {
        current_statement__ = 7;
        assign(w, cons_list(index_uni(i), nil_index_list()),
          (1 / (0.25 * slope[(i - 1)])), "assigning variable w");}
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          vars__.emplace_back(w[(sym1__ - 1)]);}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> slope;
      slope = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(slope, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> slope_flat__;
        current_statement__ = 1;
        assign(slope_flat__, nil_index_list(), context__.vals_r("slope"),
          "assigning variable slope_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 1;
          assign(slope, cons_list(index_uni(sym1__), nil_index_list()),
            slope_flat__[(pos__ - 1)], "assigning variable slope");
          current_statement__ = 1;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> cent;
      cent = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(cent, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> cent_flat__;
        current_statement__ = 2;
        assign(cent_flat__, nil_index_list(), context__.vals_r("cent"),
          "assigning variable cent_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 2;
          assign(cent, cons_list(index_uni(sym1__), nil_index_list()),
            cent_flat__[(pos__ - 1)], "assigning variable cent");
          current_statement__ = 2;
          pos__ = (pos__ + 1);}
      }
      double mu;
      mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu = context__.vals_r("mu")[(1 - 1)];
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      double sigma_free__;
      sigma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      sigma_free__ = stan::math::lb_free(sigma, 0);
      double serr;
      serr = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      serr = context__.vals_r("serr")[(1 - 1)];
      double serr_free__;
      serr_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      serr_free__ = stan::math::lb_free(serr, 0);
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        vars__.emplace_back(slope[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        vars__.emplace_back(cent[(sym1__ - 1)]);}
      vars__.emplace_back(mu);
      vars__.emplace_back(sigma_free__);
      vars__.emplace_back(serr_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("slope");
    names__.emplace_back("cent");
    names__.emplace_back("mu");
    names__.emplace_back("sigma");
    names__.emplace_back("serr");
    names__.emplace_back("w");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(L)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(L)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(L)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "slope" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "cent" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "serr");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "w" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "slope" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "cent" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "serr");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "w" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"slope\",\"type\":{\"name\":\"vector\",\"length\":" << L << "},\"block\":\"parameters\"},{\"name\":\"cent\",\"type\":{\"name\":\"vector\",\"length\":" << L << "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"serr\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" << L << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"slope\",\"type\":{\"name\":\"vector\",\"length\":" << L << "},\"block\":\"parameters\"},{\"name\":\"cent\",\"type\":{\"name\":\"vector\",\"length\":" << L << "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"serr\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" << L << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_geocline_namespace::model_geocline;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_geocline_namespace::profiles__;
}
#endif
#endif
