// Generated by rstantools.  Do not edit by hand.

/*
    bgchm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bgchm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bgchm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_Q_mix_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'Q_mix', line 29, column 1 to column 17)",
                                                      " (in 'Q_mix', line 44, column 1 to column 31)",
                                                      " (in 'Q_mix', line 46, column 2 to column 33)",
                                                      " (in 'Q_mix', line 45, column 14 to line 47, column 2)",
                                                      " (in 'Q_mix', line 45, column 1 to line 47, column 2)",
                                                      " (in 'Q_mix', line 35, column 3 to column 84)",
                                                      " (in 'Q_mix', line 33, column 15 to line 36, column 3)",
                                                      " (in 'Q_mix', line 33, column 2 to line 36, column 3)",
                                                      " (in 'Q_mix', line 32, column 14 to line 37, column 2)",
                                                      " (in 'Q_mix', line 32, column 1 to line 37, column 2)",
                                                      " (in 'Q_mix', line 40, column 2 to column 54)",
                                                      " (in 'Q_mix', line 38, column 14 to line 41, column 2)",
                                                      " (in 'Q_mix', line 38, column 1 to line 41, column 2)",
                                                      " (in 'Q_mix', line 21, column 1 to column 7)",
                                                      " (in 'Q_mix', line 22, column 1 to column 7)",
                                                      " (in 'Q_mix', line 23, column 25 to column 26)",
                                                      " (in 'Q_mix', line 23, column 28 to column 29)",
                                                      " (in 'Q_mix', line 23, column 1 to column 31)",
                                                      " (in 'Q_mix', line 24, column 31 to column 32)",
                                                      " (in 'Q_mix', line 24, column 34 to column 35)",
                                                      " (in 'Q_mix', line 24, column 1 to column 37)",
                                                      " (in 'Q_mix', line 25, column 26 to column 27)",
                                                      " (in 'Q_mix', line 25, column 1 to column 32)",
                                                      " (in 'Q_mix', line 26, column 26 to column 27)",
                                                      " (in 'Q_mix', line 26, column 1 to column 32)",
                                                      " (in 'Q_mix', line 29, column 14 to column 15)",
                                                      " (in 'Q_mix', line 44, column 26 to column 27)",
                                                      " (in 'Q_mix', line 3, column 2 to column 12)",
                                                      " (in 'Q_mix', line 15, column 7 to column 73)",
                                                      " (in 'Q_mix', line 13, column 7 to column 89)",
                                                      " (in 'Q_mix', line 12, column 9 to line 15, column 73)",
                                                      " (in 'Q_mix', line 11, column 12 to line 16, column 6)",
                                                      " (in 'Q_mix', line 10, column 7 to column 65)",
                                                      " (in 'Q_mix', line 8, column 7 to column 105)",
                                                      " (in 'Q_mix', line 7, column 11 to line 10, column 65)",
                                                      " (in 'Q_mix', line 6, column 7 to column 89)",
                                                      " (in 'Q_mix', line 5, column 6 to line 10, column 65)",
                                                      " (in 'Q_mix', line 4, column 11 to line 11, column 6)",
                                                      " (in 'Q_mix', line 4, column 2 to line 16, column 6)",
                                                      " (in 'Q_mix', line 17, column 2 to column 14)",
                                                      " (in 'Q_mix', line 2, column 79 to line 18, column 2)"};
template <typename T0__, typename T1__, typename T2__, typename T3__,
typename T4__, typename T5__, typename T6__>
stan::promote_args_t<T0__, T1__, T2__, T3__, T4__, stan::promote_args_t<T5__,
T6__>>
calc_lik(const T0__& g, const T1__& p0, const T2__& p1, const T3__& q11,
         const T4__& q10, const T5__& q00, const T6__& pl,
         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
          T1__,
          T2__,
          T3__,
          T4__, stan::promote_args_t<T5__,
          T6__>>;
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    local_scalar_t__ prob;
    prob = DUMMY_VAR__;
    
    current_statement__ = 39;
    if (logical_eq(pl, 2)) {
      current_statement__ = 37;
      if (logical_eq(g, 0)) {
        current_statement__ = 36;
        prob = stan::math::log(
                 ((((q11 * (1 - p1)) * (1 - p1)) +
                    ((q00 * (1 - p0)) * (1 - p0))) +
                   ((q10 * (1 - p1)) * (1 - p0))));
      } else {
        current_statement__ = 35;
        if (logical_eq(g, 1)) {
          current_statement__ = 34;
          prob = stan::math::log(
                   ((((((q11 * 2) * (1 - p0)) * p0) +
                       (((q00 * 2) * (1 - p1)) * p1)) +
                      ((q10 * (1 - p0)) * p1)) + ((q10 * p0) * (1 - p1))));
        } else {
          current_statement__ = 33;
          prob = stan::math::log(
                   ((((q11 * p1) * p1) + ((q00 * p0) * p0)) +
                     ((q10 * p1) * p0)));
        }
      }
    } else {
      current_statement__ = 31;
      if (logical_eq(g, 0)) {
        current_statement__ = 30;
        prob = stan::math::log(
                 ((((q11 * (1 - p1)) + (q00 * (1 - p0))) +
                    ((0.5 * q10) * (1 - p1))) + ((0.5 * q10) * (1 - p0))));
      } else {
        current_statement__ = 29;
        prob = stan::math::log(
                 ((((q11 * p1) + (q00 * p0)) + ((0.5 * q10) * p1)) +
                   ((0.5 * q10) * p0)));
      }
    }
    current_statement__ = 40;
    return prob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct calc_lik_functor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__,
typename T4__, typename T5__, typename T6__>
stan::promote_args_t<T0__, T1__, T2__, T3__, T4__, stan::promote_args_t<T5__,
T6__>>
operator()(const T0__& g, const T1__& p0, const T2__& p1, const T3__& q11,
           const T4__& q10, const T5__& q00, const T6__& pl,
           std::ostream* pstream__)  const 
{
return calc_lik(g, p0, p1, q11, q10, q00, pl, pstream__);
}
};
#include <stan_meta_header.hpp>
class model_Q_mix final : public model_base_crtp<model_Q_mix> {
private:
  int L;
  int N;
  std::vector<std::vector<int>> G;
  std::vector<std::vector<double>> ploidy;
  Eigen::Matrix<double, -1, 1> P0;
  Eigen::Matrix<double, -1, 1> P1;
 
public:
  ~model_Q_mix() { }
  
  inline std::string model_name() const final { return "model_Q_mix"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_Q_mix(stan::io::var_context& context__,
              unsigned int random_seed__ = 0,
              std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_Q_mix_namespace::model_Q_mix";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 14;
      context__.validate_dims("data initialization","L","int",
          context__.to_vec());
      L = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      L = context__.vals_i("L")[(1 - 1)];
      current_statement__ = 15;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 15;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 16;
      validate_non_negative_index("G", "N", N);
      current_statement__ = 17;
      validate_non_negative_index("G", "L", L);
      current_statement__ = 18;
      context__.validate_dims("data initialization","G","int",
          context__.to_vec(N, L));
      G = std::vector<std::vector<int>>(N, std::vector<int>(L, std::numeric_limits<int>::min()));
      
      {
        std::vector<int> G_flat__;
        current_statement__ = 18;
        assign(G_flat__, nil_index_list(), context__.vals_i("G"),
          "assigning variable G_flat__");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 18;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 18;
            assign(G,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              G_flat__[(pos__ - 1)], "assigning variable G");
            current_statement__ = 18;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 18;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 18;
        for (int sym2__ = 1; sym2__ <= L; ++sym2__) {
          current_statement__ = 18;
          current_statement__ = 18;
          check_greater_or_equal(function__, "G[sym1__, sym2__]",
                                 G[(sym1__ - 1)][(sym2__ - 1)], 0);}}
      current_statement__ = 18;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 18;
        for (int sym2__ = 1; sym2__ <= L; ++sym2__) {
          current_statement__ = 18;
          current_statement__ = 18;
          check_less_or_equal(function__, "G[sym1__, sym2__]",
                              G[(sym1__ - 1)][(sym2__ - 1)], 2);}}
      current_statement__ = 19;
      validate_non_negative_index("ploidy", "N", N);
      current_statement__ = 20;
      validate_non_negative_index("ploidy", "L", L);
      current_statement__ = 21;
      context__.validate_dims("data initialization","ploidy","double",
          context__.to_vec(N, L));
      ploidy = std::vector<std::vector<double>>(N, std::vector<double>(L, std::numeric_limits<double>::quiet_NaN()));
      
      {
        std::vector<local_scalar_t__> ploidy_flat__;
        current_statement__ = 21;
        assign(ploidy_flat__, nil_index_list(), context__.vals_r("ploidy"),
          "assigning variable ploidy_flat__");
        current_statement__ = 21;
        pos__ = 1;
        current_statement__ = 21;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 21;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 21;
            assign(ploidy,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              ploidy_flat__[(pos__ - 1)], "assigning variable ploidy");
            current_statement__ = 21;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 21;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 21;
        for (int sym2__ = 1; sym2__ <= L; ++sym2__) {
          current_statement__ = 21;
          current_statement__ = 21;
          check_greater_or_equal(function__, "ploidy[sym1__, sym2__]",
                                 ploidy[(sym1__ - 1)][(sym2__ - 1)], 0);}}
      current_statement__ = 21;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 21;
        for (int sym2__ = 1; sym2__ <= L; ++sym2__) {
          current_statement__ = 21;
          current_statement__ = 21;
          check_less_or_equal(function__, "ploidy[sym1__, sym2__]",
                              ploidy[(sym1__ - 1)][(sym2__ - 1)], 2);}}
      current_statement__ = 22;
      validate_non_negative_index("P0", "L", L);
      current_statement__ = 23;
      context__.validate_dims("data initialization","P0","double",
          context__.to_vec(L));
      P0 = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(P0, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> P0_flat__;
        current_statement__ = 23;
        assign(P0_flat__, nil_index_list(), context__.vals_r("P0"),
          "assigning variable P0_flat__");
        current_statement__ = 23;
        pos__ = 1;
        current_statement__ = 23;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 23;
          assign(P0, cons_list(index_uni(sym1__), nil_index_list()),
            P0_flat__[(pos__ - 1)], "assigning variable P0");
          current_statement__ = 23;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 23;
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        current_statement__ = 23;
        current_statement__ = 23;
        check_greater_or_equal(function__, "P0[sym1__]", P0[(sym1__ - 1)], 0);
      }
      current_statement__ = 23;
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        current_statement__ = 23;
        current_statement__ = 23;
        check_less_or_equal(function__, "P0[sym1__]", P0[(sym1__ - 1)], 1);}
      current_statement__ = 24;
      validate_non_negative_index("P1", "L", L);
      current_statement__ = 25;
      context__.validate_dims("data initialization","P1","double",
          context__.to_vec(L));
      P1 = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(P1, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> P1_flat__;
        current_statement__ = 25;
        assign(P1_flat__, nil_index_list(), context__.vals_r("P1"),
          "assigning variable P1_flat__");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
          current_statement__ = 25;
          assign(P1, cons_list(index_uni(sym1__), nil_index_list()),
            P1_flat__[(pos__ - 1)], "assigning variable P1");
          current_statement__ = 25;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 25;
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        current_statement__ = 25;
        current_statement__ = 25;
        check_greater_or_equal(function__, "P1[sym1__]", P1[(sym1__ - 1)], 0);
      }
      current_statement__ = 25;
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        current_statement__ = 25;
        current_statement__ = 25;
        check_less_or_equal(function__, "P1[sym1__]", P1[(sym1__ - 1)], 1);}
      current_statement__ = 26;
      validate_non_negative_index("Q", "N", N);
      current_statement__ = 27;
      validate_non_negative_index("H", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += N * (3 - 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_Q_mix_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> Q;
      Q = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(N, Eigen::Matrix<local_scalar_t__, -1, 1>(3));
      stan::math::fill(Q, DUMMY_VAR__);
      
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> Q_in__;
      Q_in__ = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(N, Eigen::Matrix<local_scalar_t__, -1, 1>(
        (3 - 1)));
      stan::math::fill(Q_in__, DUMMY_VAR__);
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(Q_in__, cons_list(index_uni(sym1__), nil_index_list()),
          in__.vector((3 - 1)), "assigning variable Q_in__");}
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        if (jacobian__) {
          current_statement__ = 1;
          assign(Q, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::simplex_constrain(Q_in__[(sym1__ - 1)], lp__),
            "assigning variable Q");
        } else {
          current_statement__ = 1;
          assign(Q, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::simplex_constrain(Q_in__[(sym1__ - 1)]),
            "assigning variable Q");
        }}
      {
        current_statement__ = 10;
        for (int i = 1; i <= L; ++i) {
          current_statement__ = 8;
          for (int j = 1; j <= N; ++j) {
            current_statement__ = 6;
            lp_accum__.add(
              calc_lik(G[(j - 1)][(i - 1)], P0[(i - 1)], P1[(i - 1)],
                Q[(j - 1)][(1 - 1)], Q[(j - 1)][(2 - 1)],
                Q[(j - 1)][(3 - 1)], ploidy[(j - 1)][(i - 1)], pstream__));}}
        current_statement__ = 13;
        for (int j = 1; j <= N; ++j) {
          current_statement__ = 11;
          lp_accum__.add(
            dirichlet_lpdf<false>(Q[(j - 1)], rep_vector(0.5, 3)));}
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_Q_mix_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      std::vector<Eigen::Matrix<double, -1, 1>> Q;
      Q = std::vector<Eigen::Matrix<double, -1, 1>>(N, Eigen::Matrix<double, -1, 1>(3));
      stan::math::fill(Q, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> Q_in__;
      Q_in__ = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(N, Eigen::Matrix<local_scalar_t__, -1, 1>(
        (3 - 1)));
      stan::math::fill(Q_in__, DUMMY_VAR__);
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(Q_in__, cons_list(index_uni(sym1__), nil_index_list()),
          in__.vector((3 - 1)), "assigning variable Q_in__");}
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(Q, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::simplex_constrain(Q_in__[(sym1__ - 1)]),
          "assigning variable Q");}
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(Q[(sym2__ - 1)][(sym1__ - 1)]);}}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> H;
      H = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(H, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      for (int j = 1; j <= N; ++j) {
        current_statement__ = 3;
        assign(H, cons_list(index_uni(j), nil_index_list()),
          (Q[(j - 1)][(1 - 1)] + (0.5 * Q[(j - 1)][(2 - 1)])),
          "assigning variable H");}
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        current_statement__ = 2;
        check_greater_or_equal(function__, "H[sym1__]", H[(sym1__ - 1)], 0);}
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        current_statement__ = 2;
        check_less_or_equal(function__, "H[sym1__]", H[(sym1__ - 1)], 1);}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(H[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      std::vector<Eigen::Matrix<double, -1, 1>> Q;
      Q = std::vector<Eigen::Matrix<double, -1, 1>>(N, Eigen::Matrix<double, -1, 1>(3));
      stan::math::fill(Q, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> Q_flat__;
        current_statement__ = 1;
        assign(Q_flat__, nil_index_list(), context__.vals_r("Q"),
          "assigning variable Q_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 1;
            assign(Q,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              Q_flat__[(pos__ - 1)], "assigning variable Q");
            current_statement__ = 1;
            pos__ = (pos__ + 1);}}
      }
      std::vector<Eigen::Matrix<double, -1, 1>> Q_free__;
      Q_free__ = std::vector<Eigen::Matrix<double, -1, 1>>(N, Eigen::Matrix<double, -1, 1>(
        (3 - 1)));
      stan::math::fill(Q_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 1;
        assign(Q_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::simplex_free(Q[(sym1__ - 1)]),
          "assigning variable Q_free__");}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= (3 - 1); ++sym2__) {
          vars__.emplace_back(Q_free__[(sym1__ - 1)][(sym2__ - 1)]);}}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("Q");
    names__.emplace_back("H");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(3)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "Q" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "H" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= (3 - 1); ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "Q" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "H" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"Q\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"vector\",\"length\":" << 3 << "}},\"block\":\"parameters\"},{\"name\":\"H\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"Q\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"vector\",\"length\":" << (3 - 1) << "}},\"block\":\"parameters\"},{\"name\":\"H\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_Q_mix_namespace::model_Q_mix;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_Q_mix_namespace::profiles__;
}
#endif
#endif
